### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by yuzhou898989** [xdd666t/ohos_smart_dialog#1]
ERROR: ArkTS:ERROR File: E:/AA/oh_modules/.ohpm/ohos_smart_dialog@1.3.0/oh_modules/ohos_smart_dialog/src/main/ets/model/AttachDialogModel.ets:170:55
 Cannot find name 'Size'.

**Comment by xdd666t** [comment]
最低需要 api 12

**Comment by yuzhou898989** [comment]
HarmonyOS NEXT Developer Beta1 SDK, based on OpenHarmony SDK Ohos_sdk_public 5.0.0.22 (API Version 12 Canary3)  我这边应该已经是API 12了

**Comment by xdd666t** [comment]
你就是找不到这个类, 你自己对照下吧 
![image](https://github.com/xdd666t/ohos_smart_dialog/assets/35656085/f49a4c27-6811-4c5b-bce9-246f132c831b)
