### ISSUE TITLE
全屏弹窗

### ISSUE THREAD

**Issue by xiaobai-vip** [xdd666t/ohos_smart_dialog#14]
我的工程没有设置全屏模式，但希望弹窗能够提供全屏模式，是否可以通过属性设置

**Comment by xdd666t** [comment]
这个是弹窗载体，按需盖在你自己的app上
![image](https://github.com/user-attachments/assets/3c043949-e619-4093-bc10-be75b2939082)

**Comment by xiaobai-vip** [comment]
我就是写在这的，我意思是我想让这个遮罩层能盖住安全区域，就是整个屏幕，如附件
![1727176426892](https://github.com/user-attachments/assets/c5716023-9c19-466c-9517-1a226fc58ea8)

**Comment by xdd666t** [comment]
这个需要你自己设置自己的app全屏，你自己app都不全屏，弹窗只是个载体，盖在app上了，怎么能全屏？

![image](https://github.com/user-attachments/assets/ab627fed-0c26-4413-b1d9-e3a946e3c339)

**Comment by xiaobai-vip** [comment]
？？？？  app设置不全屏，跟你的弹窗也不能全屏没有必然联系吧？app不设置全屏，某些页面也可以设置全屏，这个鸿蒙本身就支持，只是你们是在nodecontroller上加的，我试过改你们源码可以实现app不全屏，弹窗全屏盖住，只是不想改你们源码，希望你们能够提供参数设置去支持下，修改LoadingDialogComponent的布局，代码如下：
![image_130](https://github.com/user-attachments/assets/33ddcabd-c723-493d-954d-b8f8107cf46a)

**Comment by xdd666t** [comment]
这种写法太奇葩了, 这样弄会对attach等位置计算都会有问题, 对dialog各位贴边位置出现动画也会有问题，你如果坚持自己的观点，自行fork仓库去修改
