### ISSUE TITLE
如何阻塞返回事件

### ISSUE THREAD

**Issue by xiaobai-vip** [xdd666t/ohos_smart_dialog#15]
我设置成SmartBackType.block模式，虽然弹窗不会被关闭，但是会把我当前页面关闭掉了，感觉不起作用

**Comment by xdd666t** [comment]
自己检查返回事件的监听，这个参数我确定没有问题，我们项目大范围使用了这个
![image](https://github.com/user-attachments/assets/ad7037f9-f776-4bfc-ac1f-09fa265ac5b3)
