### ISSUE TITLE
showAttach的alignment不符合预期

### ISSUE THREAD

**Issue by danatechgithub4** [xdd666t/ohos_smart_dialog#16]
希望能支持 底部左对齐，还有可以设置偏移量

目前只能先用 .markAnchor({ x: -弹窗宽度的一半, y: -20 })临时解决了。

**Comment by xdd666t** [comment]
![image](https://github.com/user-attachments/assets/4d8f25ed-b167-4c57-b61e-c0d975e99efb)
![image](https://github.com/user-attachments/assets/0461d199-60ac-4313-82bb-9cb522f69204)

**Comment by danatechgithub4** [comment]
ok了，希望SmartAttachOption可以单独配置，不然其他人也会像我一样不知道。

偏移量是否可以支持？如向下偏移20

**Comment by xdd666t** [comment]
目前动画是只支持渐隐, 不支持attach的位移动画, 偏移量暂时没必要支持, 使用dialog自身margin能很简单处理

如果支持了attach的位移动画, 偏移量会一起上

还有attachAlignmentType这个属性, 一般对其都是全局的统一行为, 这个属性在flutter_smart_dialog已经一俩年了, 暂时没收到需要单独配置的场景, 不能因为不知道就在option狂加参数, 随着功能的膨胀, 这里面参数添加需要保持克制

如果真想解决问题,. 看下对应config, 或者看源码, 提issue能发现这类参数

**Comment by danatechgithub4** [comment]
为什么说‘attachAlignmentType这个属性, 一般对其都是全局的统一行为’，如果团队中其它人已经用了ohos_smart_dialog，我贸然修改后，岂不是更改了其他人的表现，同理其他人修改也会影响到我。

**Comment by xdd666t** [comment]
参考pc弹窗对齐会不会一下出现边缘对齐, 一下中心点对齐

如果一个项目里面需要俩种对齐方式，可以给出具体的业务场景，合理的话可以加上
