### ISSUE TITLE
在hmrouter库上无法使用smartdialog返回拦截 

### ISSUE THREAD

**Issue by xyggs** [xdd666t/ohos_smart_dialog#17]
大佬好，看dialog的返回拦截代码是
 NavDestination() {
      // ...
    }
    .onBackPressed(OhosSmartDialog.onBackPressed(this.onCustomBackPress))

但是在这个路由库上，entry里找不到地方注册，我在第一个子页面里注册的路由， 
  aboutToAppear(): void {
    OhosSmartDialog.registerRouter(HMRouterMgr.getPathStack('mainNav'))
  }
照着上面的拦截代码写  完全不生效，
麻烦大佬帮忙看看[
[demo.zip](https://github.com/user-attachments/files/17128294/demo.zip)
](url)

**Comment by xdd666t** [comment]
改了下你的demo，自己看下，路由注册不用管了，稍后会发布个1.6.0版本，内部无感注册路由，外部无需处理

[demo.zip](https://github.com/user-attachments/files/17172854/demo.zip)

![image](https://github.com/user-attachments/assets/869aec7a-ebeb-47bc-9fc3-16bf7abd18d5)

**Comment by xyggs** [comment]
感谢小呆呆大佬，yyds
