### ISSUE TITLE
使用HMRouter 弹窗不显示

### ISSUE THREAD

**Issue by xingzhen-ai** [xdd666t/ohos_smart_dialog#18]
@Entry
@Component
struct Index {
  modifier: MyNavModifier = new MyNavModifier()

  aboutToAppear(): void {

  }
  build() {
      Column() {
        // 使用HMNavigation容器
        HMNavigation({
          navigationId: PageConstant.MAIN_NAVIGATION_ID,  homePageUrl: PageConstant.TAB_INDEX,options: {
            standardAnimator: HMDefaultGlobalAnimator.STANDARD_ANIMATOR,
            dialogAnimator: HMDefaultGlobalAnimator.DIALOG_ANIMATOR,
            modifier: this.modifier
          }
        }){
          // here dialog init
          OhosSmartDialog()
        }
      }
      .width('100%')
      .height('100%')
  }
}

**Comment by xdd666t** [comment]
?

![image](https://github.com/user-attachments/assets/bd40955c-dd85-4c18-a76c-a2b1163a4317)

**Comment by xingzhen-ai** [comment]
可以了 没看清文档，抱歉抱歉😁
