### ISSUE TITLE
Loading框有点卡顿

### ISSUE THREAD

**Issue by zhuminjunivan** [xdd666t/ohos_smart_dialog#19]
https://github.com/user-attachments/assets/39e76c53-72a5-4746-830f-5184dbc927f7

列表加载的时候数据有点多，数据少的页面没有这个问题，不知道是不是模拟器的问题。目前也没个真机

**Comment by xdd666t** [comment]
你这是数据处理卡ui了, 处理大的数据量放在异步里面
