### ISSUE TITLE
关于checkExist判断某个弹窗是否还在

### ISSUE THREAD

**Issue by yuzhou898989** [xdd666t/ohos_smart_dialog#2]
你好，现在这边碰到一个场景，在A弹框上弹起B弹框，关闭B弹框后用checkExist判断B弹框的tag，checkExist还是会返回true，看了下是因为checkExist在寻找不到B弹框的tag后会继续判断是否存在和B弹框同类型的弹框，这对于传入tag进行判断的逻辑是否正确。
假如我这边要判断某个指定tag弹框是否存在使用checkExist就会造成判断错误

**Comment by xdd666t** [comment]
- 可以了，更新到新版本试试

```ts
"ohos_smart_dialog": "^1.5.5"
```

**Comment by yuzhou898989** [comment]
没问题了，多谢

**Comment by darren-you** [comment]
不是哥，字节上班为什么上班时间还能写开源，为什么为什么(ο´･д･)??
