### ISSUE TITLE
onDidBuild生命周期方法下调用showLoading无效

### ISSUE THREAD

**Issue by jikun2008** [xdd666t/ohos_smart_dialog#21]
### 版本信息
- DevEco Studio：[5.0.3.900]
- ohos_smart_dialog版本：[V1.6.1]

### 描述bug/需求

 ！当在onDidBuild方法下调用SmartDialog.showLoading()方法不能弹出Loading对话框,在按钮点击是可以弹出Loading对话的
 

 onDidBuild(): void {
    console.log("AxiosRequest", "onDidBuild showLoading:")
    SmartDialog.showLoading()
  }

### 问题demo
import { OhosSmartDialog, SmartDialog } from 'ohos_smart_dialog'

@Entry
@Component
struct TestActivity {
  build() {
    Stack({ alignContent: Alignment.Center }) {

      Button('dialogShow').onClick(() => {
        SmartDialog.showLoading()
      })

      OhosSmartDialog()
    }
  }

  onDidBuild(): void {
    console.log("AxiosRequest", "onDidBuild showLoading:")
    SmartDialog.showLoading()
  }
}

**Comment by xdd666t** [comment]
你这写的都是啥, 初始化写的乱七八糟, 必须盖在Navigation上,  全局有且仅有初始化一次

你每个component里面直接写, 为什么onDidBuild显示不出来? OhosSmartDialog()内部都没加载完成怎么给你显示?

还有SmartDialog不支持Router路由, 仅支持Navigation路由模式工作, 在Router路由下会有各种问题, 可参照: https://github.com/xdd666t/ohos_smart_dialog/issues/3

![image](https://github.com/user-attachments/assets/3e22a9ac-38f6-45dd-9498-e9118e44bc00)
