### ISSUE TITLE
当页面有个SmartDialog.showLoading弹窗时，在loading的弹窗底下的弹窗，无法通过tag标识去删除

### ISSUE THREAD

**Issue by xiaobai-vip** [xdd666t/ohos_smart_dialog#22]
### 版本信息
- DevEco Studio：[5.0.3.900]
- ohos_smart_dialog版本：[举例：v1.6.0]

### 描述bug/需求
请准确描述bug或需求

### 问题demo

SmartDialog.show({
          builder: showAddrAlert,
          builderArgs: result,
          clickMaskDismiss: false,
          animationTime: 0,
          backType: SmartBackType.block,
          tag:"addr"
        })
先弹一个弹窗，tag，addr
再弹一个SmartDialog.showLoading({
      builder: ezpLoading,
      tag: 'ezpLoading',
      animationTime: 0,
      backType: SmartBackType.block,
      maskBuilder: dialogCustomMask
    })
    再调用SmartDialog.dismiss({ tag: "addr" })，无法关闭addr的弹窗

**Comment by xdd666t** [comment]
- 更新下版本: 1.6.2
![image](https://github.com/user-attachments/assets/f5e73811-9d0c-4d88-9c98-113cef75433a)

**Comment by xiaobai-vip** [comment]
已解决，感谢
