### ISSUE TITLE
没有使用NavDestination全局弹窗问题

### ISSUE THREAD

**Issue by 619647373** [xdd666t/ohos_smart_dialog#23]
我的项目没有使用NavDestination 在intex里面初始化了OhosSmartDialog()组件 这时候只能在index里面显示对话框，在深层次的界面无法弹出 这时候应该怎么做支持整个app任意page页面弹出smartdialog

**Comment by xdd666t** [comment]
不支持: https://github.com/xdd666t/ohos_smart_dialog/issues/3
