### ISSUE TITLE
在flutter的容器中，调用SmartDialog.show，事件会穿透，导致点击会点触发flutter页面的事件

### ISSUE THREAD

**Issue by xiaobai-vip** [xdd666t/ohos_smart_dialog#24]
### 版本信息
- DevEco Studio：[5.0.3.900]
- ohos_smart_dialog版本：[举例：v1.6.0]

### 描述bug/需求
请准确描述bug或需求

### 问题demo

这个demo需要你有flutter的环境，在flutter的容器中，调用原生的SmartDialog.show弹窗，弹窗的事件会穿透触发到flutter页面的点击

**Comment by xdd666t** [comment]
- 完整简化demo，打个包发出来
