### ISSUE TITLE
输入法完全顶起底部弹窗

### ISSUE THREAD

**Issue by xyggs** [xdd666t/ohos_smart_dialog#25]
### 版本信息
- DevEco Studio：[5.0.3.910]
- ohos_smart_dialog版本：[v1.6.1]

### 描述bug/需求
请准确描述bug或需求
在使用底部弹窗的时候，布局里有input组件，input组件下还有个button，点击input的时候，会弹出输入法。输入法不会完全顶起弹窗，刚好弹到Input下面，会把按钮遮住，有没有办法能完全顶起整个dialog在键盘上呢
### 问题demo

[MobileDialog.zip](https://github.com/user-attachments/files/18034700/MobileDialog.zip)

**Comment by xdd666t** [comment]
弹窗把input顶起来, 也是组件input的功能, 和弹窗无关

还是我觉得键盘顶到input上, 是个很常用的功能和表现

你如果非得把按钮顶上面, 一般来说你需要自己去监控键盘高度, 然后动态去改变按钮底部的padding或者margin之类

**Comment by xyggs** [comment]
> 弹窗把input顶起来, 也是组件input的功能, 和弹窗无关
> 
> 还是我觉得键盘顶到input上, 是个很常用的功能和表现
> 
> 你如果非得把按钮顶上面, 一般来说你需要自己去监控键盘高度, 然后动态去改变按钮底部的padding或者margin之类

噢噢，因为在android的一些弹窗库，如xpopup和basePopup上，他们都是內部处理了这个问题的。那就只能自己去监听高度来margin了

**Comment by suntoooo** [comment]
老兄，你解决掉这个问题了吗？
