### ISSUE TITLE
定位弹窗，maskBuilder问题

### ISSUE THREAD

**Issue by suntoooo** [xdd666t/ohos_smart_dialog#26]
页面中间Row里面有2个button，button点击使用showAttach定位到button下面；

demo里面的maskBuilder: halfMask背景，高度可以和builder的顶部一致吗？

虽然写在builder里面就可以实现需求，但是当有动画的时候比如alignment: Alignment.Bottom，会很抽象

**Comment by suntoooo** [comment]
背景+ListView同时写在builder里面，使用动画就会很抽象，背景也是渐渐展开

**Comment by shinhaoting** [comment]
talk is cheep, show me your code! 能把代码贴出来看看吗

**Comment by xdd666t** [comment]
- 自己自定义maskBuilder

```ts
@Builder
function customMask() {
  Stack() {
    Stack().width("100%").height("100%").backgroundColor(Color.Black).opacity(0.35)
  }.margin({ top: getTargetMargin() })
}

function getTargetMargin(): number {
  const targetInfo = componentUtils.getRectangleById("targetId")
  return px2vp(targetInfo.screenOffset.y + targetInfo.size.height)
}
```

**Comment by suntoooo** [comment]
自定义的maskBuilder好像不能获取builderArgs传的参数，比如targetId是动态的

@ComponentV2
export struct TodayPlanPage {
  @Param listPosition: RefreshPositionEnum = RefreshPositionEnum.TOP
  private targetId1: string = `${Math.random() * Date.now()}`
  private targetId2: string = `${Math.random() * Date.now()}`
  build() {
    Row(){
      Button('text').id(this.targetId1).onClick(()=>{
        SmartDialog.showAttach({
          tag: '1', // 关闭tag
          targetId: this.targetId1, // 依附id
          builder: dialogUsePenetrate,
          builderArgs: this.targetId1,
          usePenetrate: true,
          maskBuilder: halfMask,
          alignment: Alignment.Bottom,
        })
      })
      Button('text').id(this.targetId2).onClick(()=>{
        SmartDialog.showAttach({
          tag: '2', // 关闭tag
          targetId: this.targetId2, // 依附id
          builder: dialogUsePenetrate,
          builderArgs: this.targetId2,
          usePenetrate: true,
          maskBuilder: halfMask,
          alignment: Alignment.Bottom,
        })
      })
    }
  }
}
@Builder
function dialogUsePenetrate(targetId: string) {
  Text(`透明遮罩事件穿透, 非透明遮罩事件不穿透` + targetId).fontColor(Color.White).padding(50)
    .borderRadius(12)
    .backgroundColor(Color.Red)
}

@Builder
function halfMask(targetId: string) {
  Stack() {
    Stack().width("100%").height("100%").backgroundColor(Color.Black).opacity(0.35)
    //Text(targetId)
  }.margin({ top: getTargetMargin() })
}

function getTargetMargin(): number {
  const targetInfo = componentUtils.getRectangleById('targetId')
  return px2vp(targetInfo.screenOffset.y + targetInfo.size.height)
}

**Comment by suntoooo** [comment]
targetId动态的，考虑到需要从后台获取列表，并且循环

**Comment by xdd666t** [comment]
- 更新下版本

![image](https://github.com/user-attachments/assets/2a564319-26c8-4f1f-8f12-0e17abb74249)
