### ISSUE TITLE
升级@ComponentV2的小建议

### ISSUE THREAD

**Issue by cjcj125125** [xdd666t/ohos_smart_dialog#27]
大佬你好，flutter中一直使用你的开源库smart_dialog,没想到鸿蒙版本也已经出来了，最近开始入手鸿蒙APP，看官方文档现在状态管理提倡使用@ComponentV2了，我就跟着入手了，但是用你这个库的时候发现你这个还是@Component，导致无法兼容，能否出一个@ComponentV2版本？如有打扰，敬请见谅，在次感谢您的开源付出！

**Comment by xdd666t** [comment]
component和componentV2可以混用, 不太明白你什么地方不兼容

**Comment by cjcj125125** [comment]
十分抱歉，我最外层忘了套 Stack控件了，赶紧大佬回复
