### ISSUE TITLE
Router路由, 多个Navigation无法弹框

### ISSUE THREAD

**Issue by Grieey** [xdd666t/ohos_smart_dialog#3]
我的app里存在多个Navigation，使用router进行切换，但是第一个navigation进行注册OhosSmartDialog.registerRouter(this.navPathStack) 后，切到第二个navigation，同样的注册，但是不起作用了。

这两个navigation使用的是router.replace的api进行切换的. 感觉是因为DialogProxy是一个单例，replace的api会销毁掉第一个navigation所在的页面，我测试了下，在replace之前，手动将DialogProxy._instance置为undefined，在第二个navigation是能正常显示的。

这种情况能进行下处理么？

**Comment by xdd666t** [comment]
给下可复现问题，可运行的最简demo

**Comment by danatechgithub4** [comment]
简单把router换成Navigation

**Comment by Grieey** [comment]
> 简单把router换成Navigation

就是没法完全替换才实现的这么畸形，app的登陆和主页没法用同一个navigation

**Comment by Grieey** [comment]
> 给下可复现问题，可运行的最简demo

[demo.zip](https://github.com/user-attachments/files/16667834/demo.zip)
操作步骤：
1. 点击页面1的弹窗，弹loading，关闭后，点击push跳转到页面2，点击弹窗，弹loading，再回到页面1，点击弹窗，无反应；
2. 直接点击replace跳转到页面2，点击弹窗无反应

**Comment by xdd666t** [comment]
看了下demo，同时也试了下，有相关的解决方法，但是会大幅度增加使用成本，而且还会导致内部的弹窗栈难以管理和难以监控处理页面切换和返回事件逻辑处理

目前可以看的出来，鸿蒙也在逐渐采用类似flutter之类的单Navigation管理页面，单Entry的Navigation演进方向

多Entry的使用方式和ohos_smart_dialog设计理念也相驳，目前不考虑兼容多OhosSmartDialog()初始入口的使用

你现在的场景，我建议你在主Entry上使用ohos_smart_dialog，使用频率较低的Entry上请勿初始化OhosSmartDialog()
