### ISSUE TITLE
初始化代码是写在任意页面都可以么还有有要求要写在哪个页面

### ISSUE THREAD

**Issue by lijq126** [xdd666t/ohos_smart_dialog#4]
你好：初始化代码是写在任意页面都可以么还有有要求要写在哪个页面

**Comment by xdd666t** [comment]
- 肯定是你页面入口的地方, 这个弹窗是盖在你路由页面上的

![image](https://github.com/user-attachments/assets/66343d1c-4343-4420-9dfc-faf1df849e95)
