### ISSUE TITLE
佬啊，这个text文字要是动态的，咋改啊

### ISSUE THREAD

**Issue by JasonYinH** [xdd666t/ohos_smart_dialog#6]
![image](https://github.com/user-attachments/assets/1b538697-8a5b-4d25-ad11-d6901deb4d64)
![image](https://github.com/user-attachments/assets/05fbd333-0b38-4bde-929e-32f7359e12fc)

**Comment by xdd666t** [comment]
![image](https://github.com/user-attachments/assets/06864d17-dc1d-4039-b348-a083880caa65)

**Comment by xdd666t** [comment]
![image](https://github.com/user-attachments/assets/1d4b1815-ee02-4d8c-80c1-61e9395e2c08)
