### ISSUE TITLE
偶发不能弹窗出来

### ISSUE THREAD

**Issue by Grieey** [xdd666t/ohos_smart_dialog#7]
![image](https://github.com/user-attachments/assets/ddc9de44-76b0-4518-91db-1084e8cf8769)
这个情况是底部弹窗，有大小，但是没有做动画出来
![image](https://github.com/user-attachments/assets/424086be-896c-4844-aa73-9a5bfd546168)
这个情况是剧中的弹窗，直接大小为0 了

以上的情况是偶发，但是一旦出现，所有的弹窗都不能弹出来了。
目前app的模式是单Navigation,上诉的情况偶发了很多次
![image](https://github.com/user-attachments/assets/bbc15c6f-c014-438f-bcc8-62897258b0fd)

**Comment by xdd666t** [comment]
给下demo

**Comment by xdd666t** [comment]
说明下, 目前我这边项目用的比较多, 暂时没没出现SmartDialog出不来的情况

如果出现这种情况, 按照flutter_smart_dialog里面别人提的issue来看, 有可能是打开弹窗时候伴随着跳转页面的操作, 导致弹窗绑定了非预期内的路由, 可能会出现这种情况

如果是类似的情况, 在ohos_smart_dialog中可以尝试将bindRouter设置为"-1"

**Comment by Grieey** [comment]
> 给下demo

demo稍后我写一个。
刚刚有一个操作路径能稳定复现，我使用全模态打开一个builder之后，再弹框不能弹窗出来，再去打开全模态的view，弹框挂在了全模态的页面上

**Comment by Grieey** [comment]
> 说明下, 目前我这边项目用的比较多, 暂时没没出现SmartDialog出不来的情况
> 
> 如果出现这种情况, 按照flutter_smart_dialog里面别人提的issue来看, 有可能是打开弹窗时候伴随着跳转页面的操作, 导致弹窗绑定了非预期内的路由, 可能会出现这种情况
> 
> 如果是类似的情况, 在ohos_smart_dialog中可以尝试将bindRouter设置为"-1"

全模态下弹框会有问题
