### ISSUE TITLE
如何做成像筛选样式的弹框？

### ISSUE THREAD

**Issue by d495988379** [xdd666t/ohos_smart_dialog#8]
如何做成像筛选样式的弹框，目前自定义弹框后 都是全屏的 有没有办法设置在某个组件的下方？

**Comment by xdd666t** [comment]
SmartDialog.showAttach

**Comment by d495988379** [comment]
SmartDialog.showAttach 方法 targetId 是组件id吗？ 表示弹框根据依照此组件设置位置吗？ 我试了下还是全屏的啊

**Comment by d495988379** [comment]
<img width="1265" alt="image" src="https://github.com/user-attachments/assets/938db46c-c3b6-482c-b1b6-1dcf4e72db46">
![image](https://github.com/user-attachments/assets/5f711752-9177-47f0-85cf-54da423014d6)

**Comment by d495988379** [comment]
<img width="720" alt="image" src="https://github.com/user-attachments/assets/2ae73d32-6683-430b-ab69-fe256a8f33d0">

**Comment by xdd666t** [comment]
demo和文档里面都写的很清楚，这个问题没必要继续讨论了
![image](https://github.com/user-attachments/assets/ff82e71a-d1cc-4a08-aca5-140ca091c470)
