### ISSUE TITLE
在aboutToAppear方法中调用show方法，无法显示弹窗

### ISSUE THREAD

**Issue by CoderXLL-new** [xdd666t/ohos_smart_dialog#9]
工程：直接用的此项目中的demo
IDE： 5.0.3.600
SDK：api12

在MainPage中添加aboutToAppear方法，执行this.viewModel.showDialog('customUseArgs')，弹窗无法显示

**Comment by CoderXLL-new** [comment]
在MainPage中执行SmartDialog.showLoading()也一样显示不出加载框

**Comment by jikun2008** [comment]
你好 你是怎么解决这个问题的啊？
